// react/src/App.tsx
import React from "react";
import update from 'immutability-helper';

import './App.css';
import { StudioLabel, StudioAxis, StudioPad, StudioSlider }  from 'studio-web-components/studio-react';
import { StudioSliderValueEvent } from 'studio-web-components/slider/slider-events';
import { Theming } from 'studio-web-components/helpers/theming';

interface iSliderData { readonly id: number, readonly value: number };

export default class App extends React.Component {
  theming = new Theming();

  constructor(props: any) {
    super(props);
    this.state = {
      sliders: [
        { id: 0, value: 0 },
        { id: 1, value: 25 },
        { id: 2, value: 50 },
        { id: 3, value: 75 },
      ]
    };
  }

  get sliders(): Readonly<iSliderData[]> { return (this.state as any).sliders; }

  onSliderValue(event: Event, id: number) {
    const studioSliderEvent = (event as StudioSliderValueEvent);
    const newValue = studioSliderEvent.studio.value;
    const newState = update(this.state, {
      sliders: {[id]: { value: { $set: newValue}}}
    });
    this.setState(newState);
  }

  render() {
    return (
      <div id="app" className="App">
        <div className="studio-column">
          <StudioLabel>Studiö Web Components</StudioLabel>
          <StudioLabel>with React</StudioLabel>
          <div className="studio-row">
          <StudioPad className="button" onClick={() => this.theming.toggleTheme()}>Theme<div slot="secondary">Toggle</div></StudioPad>
          <StudioPad className="button" onClick={() => this.theming.toggleScale()}>Scale<div slot="secondary">Toggle</div></StudioPad>
          </div>
          <div className="studio-row">
            {this.sliders.map((slider) => {
              return (
                <StudioSlider value={slider.value} end-value="100" step={1} key={slider.id}
                  studioSliderValue={e => this.onSliderValue(e, slider.id)}>
                  <StudioAxis fit slot="cursor-range"></StudioAxis>
                  <StudioLabel slot="label-start" className="slider-label">{slider.value}</StudioLabel>
                </StudioSlider>
              );
            })}
          </div>
        </div>
      </div>
    );
  }
}

// angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { StudioSliderValueEvent } from 'studio-web-components/slider/slider-events';
import { Theming } from 'studio-web-components/helpers/theming';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  theming = new Theming();
  // Data for studio-slider elements using *ngFor
  sliders: any[] = [
    { value: 0 },
    { value: 25 },
    { value: 50 },
    { value: 75 }
  ];

  // Update the slider data when the slider value changes
  onSliderValue(event: Event, sliderIndex: any) {
    const value: number = (event as StudioSliderValueEvent).studio.value;
    this.sliders[sliderIndex].value = value;
  }
}

<div class="studio-column">
  <!-- A simple heading using studio-label -->
  <studio-label>Studiö Web Components</studio-label>
  <studio-label>with Angular</studio-label>
  <!-- Using studio-pad as buttons to toggle theme and scale -->
  <div class="studio-row">
    <!-- Toggle theme -->
    <studio-pad class="button" (click)="theming.toggleTheme()">Theme
      <div slot="secondary">Toggle</div>
    </studio-pad>
    <!-- Toggle scale -->
    <studio-pad class="button" (click)="theming.toggleScale()">Scale
      <div slot="secondary">Toggle</div>
    </studio-pad>
  </div>
  <div class="studio-row">
    <!-- Using *ngFor to display 4 studio-slider elements -->
    <div *ngFor="let slider of sliders; let sliderIndex = index;">
      <studio-slider [value]="slider.value" end-value="100" step="1"
                     (studio-slider-value)="onSliderValue($event, sliderIndex)">
        <!-- Display the slider value using studio-label -->
        <studio-label slot="label-start" class="slider-label">{{slider.value}}</studio-label>
        <!-- Some tick marks using studio-ruler-->
        <studio-axis slot="cursor-range" fit></studio-axis>
      </studio-slider>
    </div>
  </div>
</div>
